## Importing packages and setting paths ##

In [3]:
import pandas as pd
import nibabel as nib
from glob import glob
import numpy as np

In [4]:
#first load up the label dseg table
atlas='brainnetome'

df_labels = pd.read_csv(f'resources/atlas/atlas-{atlas}_dseg.tsv',sep='\t')
df_labels

df_network_names = df_labels.networks.unique()
df_network_names

#df_tabular = pd.read_csv(snakemake.input.tsv,sep='\t')
df_tabular = pd.read_csv('results/analysis/df_tabular.csv',sep='\t')

df_tabular

,participant_id,dataset,age,sex,age_seizure_onset,age_ep_diagnosis,ep_duration_first_scan,seizure_duration_first_scan,pnes,benign_rolandic,...,NFC_Limbic,NFC_Cont,NFC_Default,NSC_Vis,NSC_SomMot,NSC_DorsAttn,NSC_SalVentAttn,NSC_Limbic,NSC_Cont,NSC_Default
0,sub-HCD0001305,HCP,11.916667,M,NaN,NaN,NaN,NaN,NaN,NaN,...,0.200019,0.257366,0.135539,3.885010,5.062987,8.027959,7.580041,5.651460,7.296828,7.935002
1,sub-HCD0021614,HCP,9.166667,F,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.000347,0.147511,0.039930,4.216869,4.518716,7.629381,7.669835,6.542762,7.380725,8.132475
2,sub-HCD0026119,HCP,15.166667,F,NaN,NaN,NaN,NaN,NaN,NaN,...,0.093052,0.082952,0.052142,4.770188,4.651514,8.898358,7.785734,6.827971,7.798882,8.109647
3,sub-HCD0041822,HCP,17.416667,M,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.001980,-0.008243,0.010302,4.030981,4.773803,8.804379,7.742067,6.960907,8.298339,8.540095
4,sub-HCD0042420,HCP,18.333333,M,NaN,NaN,NaN,NaN,NaN,NaN,...,0.091706,0.153798,0.082643,4.350406,4.851836,9.014367,7.819415,6.471102,8.094806,8.193476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,sub-029,LOBE,16.000000,M,15.0,15.0,1.0,1.0,0.0,0.0,...,0.467955,0.392260,0.372756,4.093281,4.358512,7.515517,7.141540,6.457969,6.372687,7.238880
358,sub-031,LOBE,9.000000,M,4.0,6.0,3.0,5.0,0.0,0.0,...,0.228163,0.205326,0.162994,4.788529,5.042807,8.379897,7.876680,7.567836,8.409854,8.806705
359,sub-033,LOBE,7.000000,M,4.0,NaN,NaN,3.0,0.0,0.0,...,-0.029804,0.006911,-0.027776,4.030132,4.791794,7.306059,7.469537,6.275113,7.390206,8.429542
360,sub-035,LOBE,7.000000,M,2.0,4.0,3.0,5.0,0.0,0.0,...,0.035206,-0.010172,0.008450,4.027565,4.504583,7.768704,7.925532,6.047853,7.735365,8.119764
361,sub-038,LOBE,10.000000,F,7.0,7.0,3.0,3.0,0.0,0.0,...,0.092600,0.031936,0.105244,4.227500,5.029610,8.060599,7.408326,5.981137,7.941198,8.547162

In [5]:
subject = '040'
dataset = 'LOBE'

In [6]:
# Schaefer Patterns
#fc_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-schaefer_bold.pconn.nii'
#sc_pattern='results/{dataset}/sub-{subject}/dwi/sub-{subject}_den-91k_atlas-schaefer_struc.pconn.nii'
#sfc_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-schaefer_sfc.pscalar.nii'

# Brainnetome Patterns
fc_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_bold.pconn.nii'
sc_pattern='results/{dataset}/sub-{subject}/dwi/sub-{subject}_den-91k_atlas-brainnetome_struc.pconn.nii'
sfc_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii'

In [7]:
sfc_paths={}
#sfc_paths['HCP'] = sorted(glob(sfc_pattern.format(dataset='HCP',subject='*')))
sfc_paths['LOBE'] = sorted(glob(sfc_pattern.format(dataset='LOBE',subject='040')))

fc_paths={}
#fc_paths['HCP'] = sorted(glob(fc_pattern.format(dataset='HCP',subject='*')))
fc_paths['LOBE'] = sorted(glob(fc_pattern.format(dataset='LOBE',subject='040')))

sc_paths={}
#sc_paths['HCP'] = sorted(glob(sc_pattern.format(dataset='HCP',subject='*')))
sc_paths['LOBE'] = sorted(glob(sc_pattern.format(dataset='LOBE',subject='040')))

print(sfc_paths)
#print(fc_paths)
#print(sc_paths)

{'LOBE': ['results/LOBE/sub-040/func/sub-040_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_sfc.pscalar.nii']}

In [8]:
sfc={}
fc={}
sc={}
num_parcels = nib.load(sfc_paths['LOBE'][0]).get_fdata().shape[1]
datasets=['LOBE']
for dataset in datasets:
    sfc[dataset] = np.concatenate(  [ nib.load(path).get_fdata()  for path in sfc_paths[dataset]] ,axis=0)
    fc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in fc_paths[dataset]] ,axis=0)
    sc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in sc_paths[dataset]] ,axis=0)

In [9]:
# Brainnetome Patterns
fc_network_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_netbold.pconn.nii'
sc_network_pattern='results/{dataset}/sub-{subject}/dwi/sub-{subject}_den-91k_atlas-brainnetome_netstruc.pconn.nii'
sfc_network_pattern='results/{dataset}/sub-{subject}/func/sub-{subject}_task-rest_den-91k_desc-preproc_denoise-24HMP8PhysSpikeReg_fwhm-5_atlas-brainnetome_netsfc.pconn.nii'

datasets=['LOBE']

In [10]:
sfc_netpaths={}
sfc_netpaths['LOBE'] = sorted(glob(sfc_network_pattern.format(dataset='LOBE',subject='040')))

fc_netpaths={}
fc_netpaths['LOBE'] = sorted(glob(fc_network_pattern.format(dataset='LOBE',subject='040')))

sc_netpaths={}
sc_netpaths['LOBE'] = sorted(glob(sc_network_pattern.format(dataset='LOBE',subject='040')))

#print(sfc_netpaths)
#print(fc_netpaths)
#print(sc_netpaths)

# Within-Network Masking

## SFC

In [82]:
sfc={}
fc={}
sc={}
num_parcels = nib.load(sfc_netpaths['LOBE'][0]).get_fdata().shape[1]

for dataset in datasets:

    sfc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in sfc_netpaths[dataset]] ,axis=0)  
    #for path in sfc_netpaths[dataset]] ,axis=0)
    fc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in fc_netpaths[dataset]] ,axis=0)
    sc[dataset] = np.concatenate(  [ nib.load(path).get_fdata().reshape((1,num_parcels,num_parcels))  for path in sc_netpaths[dataset]] ,axis=0)

In [83]:
sfc['LOBE']

array([[[ 0.21759956,  0.16465794,  0.11350711,  0.06251424,
          0.17675048,         nan,         nan,  0.05920265],
        [ 0.16465794,  0.05991117,  0.01938526,  0.00728759,
          0.03202929,         nan,         nan,  0.01020335],
        [ 0.11350711,  0.01938526,  0.28980474,  0.13987804,
         -0.02744747,         nan,         nan, -0.0629219 ],
        [ 0.06251424,  0.00728759,  0.13987804,  0.33977994,
          0.185539  ,         nan,         nan,  0.04935474],
        [ 0.17675048,  0.03202929, -0.02744747,  0.185539  ,
          0.12967571,         nan,         nan,  0.12407312],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,         nan],
        [ 0.05920265,  0.01020335, -0.0629219 ,  0.04935474,
          0.12407312,         nan,         nan,  0.28960975]]])

In [84]:
sfc['LOBE'].shape

(1, 8, 8)

In [85]:

# Assuming this is your original x2 matrix
x2 = sfc['LOBE']  # (1, 8, 8)

# Check where NaN values are present in the original matrix
nan_positions = np.isnan(x2[0, :, :])
print("NaN positions in original matrix:")
print(nan_positions)

NaN positions in original matrix:
[[False False False False False  True  True False]
 [False False False False False  True  True False]
 [False False False False False  True  True False]
 [False False False False False  True  True False]
 [False False False False False  True  True False]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [False False False False False  True  True False]]

In [107]:
# Assuming x2 is of shape (1, 8, 8)
x2 = fc['LOBE']  # (1, 8, 8)
num_parcels = x2.shape[1]  # Assuming it's 8

for s in range(x2.shape[0]):
    conn = x2[s, :, :]  # Extract the 8x8 matrix for each subject (if there are multiple)
    
    # Create a mask where only the diagonal elements are True
    mask = np.eye(num_parcels, dtype=bool)  # A boolean mask with True on the diagonal, False elsewhere
    
    # Create a copy of the original matrix to avoid modifying the original data directly
    conn_copy = conn.copy()

    # Set off-diagonal elements to NaN, but preserve the diagonal
    conn_copy[~mask] = np.nan  # Set non-diagonal elements to NaN
    
    x2[s, :, :] = conn_copy  # Update the matrix with the modified values

In [108]:
x2

array([[[0.18443059,        nan,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan, 0.17166353,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan, 0.26685736,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan, 0.14109458,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan, 0.31074747,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan, 0.2109079 ]]])

In [109]:
x2 = np.nanmean(x2,axis=2)

/tmp/ipykernel_1436892/4240356946.py:1: RuntimeWarning: Mean of empty slice
  x2 = np.nanmean(x2,axis=2)

## SC

In [54]:
sc['LOBE']

array([[[27.62014391, 29.14928043, 25.44034907, 20.18212951,
         35.94483735,  4.79818473,  6.90563085,  8.47028586],
        [29.14928043, 38.31675361,  9.87773292, 12.71421918,
         23.23746135, 10.51488041,  7.13316982,  7.98815979],
        [25.44034907,  9.87773292, 41.77355372, 30.10598719,
         10.96085608,  9.68868791, 13.07419725, 10.92315399],
        [20.18212951, 12.71421918, 30.10598719, 56.86251146,
         32.30358134,  6.62668745,  4.88435086, 15.63776809],
        [35.94483735, 23.23746135, 10.96085608, 32.30358134,
         34.4624617 ,  5.12282371,  5.51976728, 11.76025998],
        [ 4.79818473, 10.51488041,  9.68868791,  6.62668745,
          5.12282371, 22.54014362,  7.10969137, 11.56976856],
        [ 6.90563085,  7.13316982, 13.07419725,  4.88435086,
          5.51976728,  7.10969137, 57.72286565,  6.1626869 ],
        [ 8.47028586,  7.98815979, 10.92315399, 15.63776809,
         11.76025998, 11.56976856,  6.1626869 , 20.97413566]]])

In [60]:
x2 = sc['LOBE']  # (1, 8, 8)
num_parcels = x2.shape[1]  # Assuming it's 8

for s in range(x2.shape[0]):
    conn = x2[s, :, :]  # Extract the 8x8 matrix for each subject (if there are multiple)
    
    # Create a mask where only the diagonal elements are True
    mask = np.eye(num_parcels, dtype=bool)  # A boolean mask with True on the diagonal, False elsewhere
    
    # Create a copy of the original matrix to avoid modifying the original data directly
    conn_copy = conn.copy()

    # Set off-diagonal elements to NaN, but preserve the diagonal
    conn_copy[~mask] = np.nan  # Set non-diagonal elements to NaN
    
    x2[s, :, :] = conn_copy  # Update the matrix with the modified values'LOBE'].shape

In [61]:
x2

array([[[27.62014391,         nan,         nan,         nan,
                 nan,         nan,         nan,         nan],
        [        nan, 38.31675361,         nan,         nan,
                 nan,         nan,         nan,         nan],
        [        nan,         nan, 41.77355372,         nan,
                 nan,         nan,         nan,         nan],
        [        nan,         nan,         nan, 56.86251146,
                 nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,
         34.4624617 ,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,
                 nan, 22.54014362,         nan,         nan],
        [        nan,         nan,         nan,         nan,
                 nan,         nan, 57.72286565,         nan],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan, 20.97413566]]])

In [62]:
x2 = np.nanmean(x2,axis=2)

In [63]:
x2

array([[27.62014391, 38.31675361, 41.77355372, 56.86251146, 34.4624617 ,
        22.54014362, 57.72286565, 20.97413566]])

## FC

In [64]:
fc['LOBE']

array([[[0.18443059,        nan,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan, 0.17166353,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan, 0.26685736,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan, 0.14109458,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan, 0.31074747,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan, 0.2109079 ]]])

In [65]:
x2 = fc['LOBE']  # (1, 8, 8)
num_parcels = x2.shape[1]  # Assuming it's 8

for s in range(x2.shape[0]):
    conn = x2[s, :, :]  # Extract the 8x8 matrix for each subject (if there are multiple)
    
    # Create a mask where only the diagonal elements are True
    mask = np.eye(num_parcels, dtype=bool)  # A boolean mask with True on the diagonal, False elsewhere
    
    # Create a copy of the original matrix to avoid modifying the original data directly
    conn_copy = conn.copy()

    # Set off-diagonal elements to NaN, but preserve the diagonal
    conn_copy[~mask] = np.nan  # Set non-diagonal elements to NaN
    
    x2[s, :, :] = conn_copy  # Update the matrix with the modified values'LOBE'].shape

In [66]:
x2

array([[[0.18443059,        nan,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan, 0.17166353,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan, 0.26685736,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan, 0.14109458,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan, 0.31074747,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan,
                nan,        nan, 0.2109079 ]]])

In [67]:
x2 = np.nanmean(x2,axis=2)

/tmp/ipykernel_1436892/4240356946.py:1: RuntimeWarning: Mean of empty slice
  x2 = np.nanmean(x2,axis=2)

In [68]:
x2

array([[0.18443059, 0.17166353, 0.26685736, 0.14109458, 0.31074747,
               nan,        nan, 0.2109079 ]])

# Adding between-network to df

In [89]:
print(df_tabular)

     participant_id dataset        age sex  age_seizure_onset  \
0    sub-HCD0001305     HCP  11.916667   M                NaN
1    sub-HCD0021614     HCP   9.166667   F                NaN
2    sub-HCD0026119     HCP  15.166667   F                NaN
3    sub-HCD0041822     HCP  17.416667   M                NaN
4    sub-HCD0042420     HCP  18.333333   M                NaN
..              ...     ...        ...  ..                ...
357         sub-029    LOBE  16.000000   M               15.0
358         sub-031    LOBE   9.000000   M                4.0
359         sub-033    LOBE   7.000000   M                4.0
360         sub-035    LOBE   7.000000   M                2.0
361         sub-038    LOBE  10.000000   F                7.0

     age_ep_diagnosis  ep_duration_first_scan  seizure_duration_first_scan  \
0                 NaN                     NaN                          NaN
1                 NaN                     NaN                          NaN
2                 NaN                     NaN                          NaN
3                 NaN                     NaN                          NaN
4                 NaN                     NaN                          NaN
..                ...                     ...                          ...
357              15.0                     1.0                          1.0
358               6.0                     3.0                          5.0
359               NaN                     NaN                          3.0
360               4.0                     3.0                          5.0
361               7.0                     3.0                          3.0

     pnes  benign_rolandic  ... NFC_Limbic  NFC_Cont  NFC_Default   NSC_Vis  \
0     NaN              NaN  ...   0.200019  0.257366     0.135539  3.885010
1     NaN              NaN  ...  -0.000347  0.147511     0.039930  4.216869
2     NaN              NaN  ...   0.093052  0.082952     0.052142  4.770188
3     NaN              NaN  ...  -0.001980 -0.008243     0.010302  4.030981
4     NaN              NaN  ...   0.091706  0.153798     0.082643  4.350406
..    ...              ...  ...        ...       ...          ...       ...
357   0.0              0.0  ...   0.467955  0.392260     0.372756  4.093281
358   0.0              0.0  ...   0.228163  0.205326     0.162994  4.788529
359   0.0              0.0  ...  -0.029804  0.006911    -0.027776  4.030132
360   0.0              0.0  ...   0.035206 -0.010172     0.008450  4.027565
361   0.0              0.0  ...   0.092600  0.031936     0.105244  4.227500

     NSC_SomMot  NSC_DorsAttn  NSC_SalVentAttn  NSC_Limbic  NSC_Cont  \
0      5.062987      8.027959         7.580041    5.651460  7.296828
1      4.518716      7.629381         7.669835    6.542762  7.380725
2      4.651514      8.898358         7.785734    6.827971  7.798882
3      4.773803      8.804379         7.742067    6.960907  8.298339
4      4.851836      9.014367         7.819415    6.471102  8.094806
..          ...           ...              ...         ...       ...
357    4.358512      7.515517         7.141540    6.457969  6.372687
358    5.042807      8.379897         7.876680    7.567836  8.409854
359    4.791794      7.306059         7.469537    6.275113  7.390206
360    4.504583      7.768704         7.925532    6.047853  7.735365
361    5.029610      8.060599         7.408326    5.981137  7.941198

     NSC_Default
0       7.935002
1       8.132475
2       8.109647
3       8.540095
4       8.193476
..           ...
357     7.238880
358     8.806705
359     8.429542
360     8.119764
361     8.547162

[362 rows x 978 columns]

In [91]:
#add SFC network avgs to tabular df

# Define mock data for x1 and x2
data_ = {'LOBE': x2}  # Replace x1 and x2 with your actual data

# Example network names (replace with your actual network names)
df_network_names = ['Network1', 'Network2', 'Network3', 'Network4', 'Network5', 'Network6', 'Network7', 'Network8']  

# Example datasets
datasets = ['LOBE']

# Example subjects dictionary (replace with actual subject IDs if needed)
subjects = {'LOBE': ['sub-009']}  

# Assuming df_tabular is already loaded as a DataFrame (replace with your actual file if needed)
# Example of what df_tabular might look like if it were loaded
# df_tabular = pd.read_csv("your_file.csv")  # Or however you load df_tabular

# List to collect merged DataFrames
df_list = []

for dataset in datasets:
    # Create DataFrame for the current dataset
    df_ = pd.DataFrame(data_[dataset], columns=[f'NSFC_{name}' for name in df_network_names])
    
    # Filter the main df_tabular by the current dataset
    df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    
    # Add the participant_ids from the subjects
    df_['participant_id'] = subjects[dataset]
    
    # Merge the new df_ with df_tabular_ on 'participant_id'
    df_merged_ = pd.merge(df_tabular_, df_, how='left', on='participant_id')
    
    # Append merged DataFrame to the list
    df_list.append(df_merged_)

# Concatenate all merged DataFrames
df_tabular_final = pd.concat(df_list)

# Display the final DataFrame
df_tabular_final

,participant_id,dataset,age,sex,age_seizure_onset,age_ep_diagnosis,ep_duration_first_scan,seizure_duration_first_scan,pnes,benign_rolandic,...,NSC_Cont,NSC_Default,NSFC_Network1,NSFC_Network2,NSFC_Network3,NSFC_Network4,NSFC_Network5,NSFC_Network6,NSFC_Network7,NSFC_Network8
0,sub-006,LOBE,9.0,M,7.0,8.0,1.0,2.0,0.0,0.0,...,7.097794,7.533409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sub-007,LOBE,9.0,F,7.0,7.0,2.0,2.0,0.0,0.0,...,7.850586,8.161856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sub-009,LOBE,8.0,M,2.0,8.0,0.0,6.0,0.0,0.0,...,7.934972,8.000003,0.184431,0.171664,0.266857,0.141095,0.310747,NaN,NaN,0.210908
3,sub-010,LOBE,15.0,M,7.0,7.0,8.0,8.0,0.0,0.0,...,7.446570,7.673076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,sub-012,LOBE,14.0,F,4.0,10.0,4.0,10.0,0.0,0.0,...,7.798454,7.919612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,sub-013,LOBE,15.0,F,13.0,14.0,1.0,2.0,0.0,0.0,...,6.787390,8.240192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,sub-014,LOBE,14.0,M,9.0,9.0,5.0,5.0,0.0,0.0,...,6.931214,6.931229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,sub-015,LOBE,10.0,M,7.0,7.0,3.0,3.0,0.0,1.0,...,7.125103,8.940187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,sub-017,LOBE,15.0,F,10.0,10.0,5.0,5.0,0.0,0.0,...,8.214334,8.586060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,sub-019,LOBE,17.0,F,16.0,16.0,1.0,1.0,0.0,0.0,...,8.004336,8.213125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,sub-020,LOBE,15.0,F,8.0,10.0,5.0,7.0,0.0,0.0,...,7.212081,7.177974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,sub-022,LOBE,11.0,F,3.0,5.0,6.0,8.0,0.0,0.0,...,7.445807,8.088465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,sub-024,LOBE,11.0,M,8.0,9.0,2.0,3.0,0.0,0.0,...,6.974796,8.101657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,sub-025,LOBE,18.0,F,8.0,17.0,1.0,10.0,0.0,0.0,...,7.447820,7.901872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,sub-026,LOBE,16.0,M,2.0,12.0,4.0,14.0,0.0,0.0,...,7.456556,8.203762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,sub-027,LOBE,7.0,M,4.0,5.0,3.0,3.0,0.0,0.0,...,7.004652,7.430482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,sub-029,LOBE,16.0,M,15.0,15.0,1.0,1.0,0.0,0.0,...,6.372687,7.238880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,sub-031,LOBE,9.0,M,4.0,6.0,3.0,5.0,0.0,0.0,...,8.409854,8.806705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,sub-033,LOBE,7.0,M,4.0,NaN,NaN,3.0,0.0,0.0,...,7.390206,8.429542,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,sub-035,LOBE,7.0,M,2.0,4.0,3.0,5.0,0.0,0.0,...,7.735365,8.119764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,sub-038,LOBE,10.0,F,7.0,7.0,3.0,3.0,0.0,0.0,...,7.941198,8.547162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Between Network Masking

## SFC

In [103]:
# Assuming x2 is of shape (1, 8, 8)
x2 = sfc['LOBE']  # (1, 8, 8)
num_parcels = x2.shape[1]  # Assuming it's 8

# Loop over each "slice" in x2 (assuming only one slice, so loop over the first element)
for s in range(x2.shape[0]):
    conn = x2[s, :, :]  # Extract the 8x8 matrix for the current subject
    
    # Set the diagonal to NaN 
    mask_diag = np.eye(num_parcels, dtype=bool)
    conn[mask_diag] = np.nan
    
    # Set the lower triangle to NaN (lower triangular indices)
    mask_lower_triangle = np.tril(np.ones((num_parcels, num_parcels)), k=-1)  # `k=-1` excludes the diagonal
    conn[mask_lower_triangle == 1] = np.nan
    
    # Now loop over the upper triangle to gather values for each "mixture"
    for i in range(num_parcels):
        for j in range(i+1, num_parcels):
            # You are looking at the upper triangular part (i < j)
            # This will collect values from (i, j) where i < j
            value = conn[i, j]  # Get the value for that specific pair (i, j)

    # Update the matrix after modification (just for reference)
    x2[s, :, :] = conn  # If you want to keep the modified matrix

In [104]:
x2

array([[[        nan,  0.16465794,  0.11350711,  0.06251424,
          0.17675048,         nan,         nan,  0.05920265],
        [        nan,         nan,  0.01938526,  0.00728759,
          0.03202929,         nan,         nan,  0.01020335],
        [        nan,         nan,         nan,  0.13987804,
         -0.02744747,         nan,         nan, -0.0629219 ],
        [        nan,         nan,         nan,         nan,
          0.185539  ,         nan,         nan,  0.04935474],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,  0.12407312],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,         nan]]])

# Naming between-network values

In [105]:
x2

array([[[        nan,  0.16465794,  0.11350711,  0.06251424,
          0.17675048,         nan,         nan,  0.05920265],
        [        nan,         nan,  0.01938526,  0.00728759,
          0.03202929,         nan,         nan,  0.01020335],
        [        nan,         nan,         nan,  0.13987804,
         -0.02744747,         nan,         nan, -0.0629219 ],
        [        nan,         nan,         nan,         nan,
          0.185539  ,         nan,         nan,  0.04935474],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,  0.12407312],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,
                 nan,         nan,         nan,         nan]]])

In [106]:
# Example: x2 is a (1, 8, 8) matrix
x2 = x2[0]  # Now x2 is shape (8, 8)

# Define your network names
df_network_names = ['Network1', 'Network2', 'Network3', 'Network4', 'Network5', 'Network6', 'Network7', 'Network8']

# Example datasets and subjects
datasets = ['LOBE']
subjects = {'LOBE': ['sub-009']}  

# Assuming df_tabular is already loaded
# df_tabular = pd.read_csv("your_file.csv")  # Or however you load df_tabular

# List to collect merged DataFrames
df_list = []

for dataset in datasets:
    # Create column names: NSFC_network1_network2
    colnames=[]
    for i in range(len(df_network_names):
        for j in range(i, len(df_network_names))
            if i>j:
                continue
            colnames.append(f'NSFC_{df_network_names[i]}_{df_network_names[j]}')
                
                

    # Flatten the upper triangle of x2 into a 1D array to match the number of columns
    upper_triangle_values = [x2[i, j] for i in range(len(df_network_names)) for j in range(i, len(df_network_names))]

    # Create a DataFrame for the current dataset using the flattened upper triangle values
    df_ = pd.DataFrame([upper_triangle_values], columns=colnames)
    
    # Filter the main df_tabular by the current dataset
    df_tabular_ = df_tabular.query(f"dataset == '{dataset}'")
    
    # Add the participant_ids from the subjects
    df_['participant_id'] = subjects[dataset]
    
    # Merge the new df_ with df_tabular_ on 'participant_id'
    df_merged_ = pd.merge(df_tabular_, df_, how='left', on='participant_id')
    
    # Append merged DataFrame to the list
    df_list.append(df_merged_)

# Concatenate all merged DataFrames
df_tabular_final = pd.concat(df_list)

# Display the final DataFrame
df_tabular_final

,participant_id,dataset,age,sex,age_seizure_onset,age_ep_diagnosis,ep_duration_first_scan,seizure_duration_first_scan,pnes,benign_rolandic,...,NSFC_Network5_Network5,NSFC_Network5_Network6,NSFC_Network5_Network7,NSFC_Network5_Network8,NSFC_Network6_Network6,NSFC_Network6_Network7,NSFC_Network6_Network8,NSFC_Network7_Network7,NSFC_Network7_Network8,NSFC_Network8_Network8
0,sub-006,LOBE,9.0,M,7.0,8.0,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sub-007,LOBE,9.0,F,7.0,7.0,2.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sub-009,LOBE,8.0,M,2.0,8.0,0.0,6.0,0.0,0.0,...,NaN,NaN,NaN,0.124073,NaN,NaN,NaN,NaN,NaN,NaN
3,sub-010,LOBE,15.0,M,7.0,7.0,8.0,8.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,sub-012,LOBE,14.0,F,4.0,10.0,4.0,10.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,sub-013,LOBE,15.0,F,13.0,14.0,1.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,sub-014,LOBE,14.0,M,9.0,9.0,5.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,sub-015,LOBE,10.0,M,7.0,7.0,3.0,3.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,sub-017,LOBE,15.0,F,10.0,10.0,5.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,sub-019,LOBE,17.0,F,16.0,16.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,sub-020,LOBE,15.0,F,8.0,10.0,5.0,7.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,sub-022,LOBE,11.0,F,3.0,5.0,6.0,8.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,sub-024,LOBE,11.0,M,8.0,9.0,2.0,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,sub-025,LOBE,18.0,F,8.0,17.0,1.0,10.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,sub-026,LOBE,16.0,M,2.0,12.0,4.0,14.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,sub-027,LOBE,7.0,M,4.0,5.0,3.0,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,sub-029,LOBE,16.0,M,15.0,15.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,sub-031,LOBE,9.0,M,4.0,6.0,3.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,sub-033,LOBE,7.0,M,4.0,NaN,NaN,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,sub-035,LOBE,7.0,M,2.0,4.0,3.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,sub-038,LOBE,10.0,F,7.0,7.0,3.0,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN